### ISSUE TITLE
 No module named 'expert'

### ISSUE THREAD

**Issue by robot-Yang** [omron-sinicx/when2replan#1]
Hello, thank you for the open-source code.

However, I got the following error when I run:
```
python3 run.py\
        run.model_dir="../trained_model"\
        run.model_name="DijkstraxDWA/16pillar.zip"\
        run.log_save_dir="run/DijkstraxDWA/16pillar"\
        run.navigation_scenarios="config/scenario/sixteen_pillar/random.yaml"\
        run.view_animation=False\
        run.seeds=[37]\
        navigation.common.global_planner="Dijkstra"\
        navigation.common.local_planner="DWA"

```

```
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    from expert import ExpertActor
ModuleNotFoundError: No module named 'expert'
```
Could you please help me? thanks in advance.

**Comment by kohonda** [comment]
@robot-Yang 
Thank you for your interest. It seems I had imported unused packages that weren't in this repo. I've now fixed the issue.

**Comment by robot-Yang** [comment]
@kohonda 
Thank you for the quick response.
However, I got another issue when I ran the same previous command.

```
Traceback (most recent call last):
  File "run.py", line 205, in main
    params = HyperParameters(config=config, mode="run")
  File "mypath/when2replan/scripts/utils.py", line 48, in __init__
    yaml.safe_load(open(navigation_scenario_path, "r"))
FileNotFoundError: [Errno 2] No such file or directory: 'mypath/when2replan/scripts/../c'
```

**Comment by tadashiK** [comment]
@robot-Yang Hi, I'm a coauthor of this paper. It seems that the code is failing to find a correct yaml file that describes navigation_scenarios. So, would you please tell us the command you used?

As described in README, navigation_scenarios can be provided as an option, so maybe the error is due to a wrongly specified path to a yaml file. Indeed the path shown in the error message doesn't make sense.

Oops, you did in the first comment. Please forget about this comment above.

**Comment by kohonda** [comment]
@robot-Yang 
Sorry. I found that the command line written in the README was incorrect. Can you run the following command again?

```
cd scripts
python3 run.py\
        run.model_dir="../trained_model"\
        run.model_name="DijkstraxDWA/16pillar.zip"\
        run.log_save_dir="run/DijkstraxDWA/16pillar"\
        run.navigation_scenarios=["config/scenario/sixteen_pillar/random.yaml"]\
        run.view_animation=False\
        run.seeds=[37]\
        navigation.common.global_planner="Dijkstra"\
        navigation.common.local_planner="DWA"
```

**Comment by robot-Yang** [comment]
@tadashiK 
Thank you for the reply.

@kohonda 
Thank you for the corrected command.
Now I can successfully run it.

FYI, when I run `python3 pygame_visualizer.py main ../log/run/latest/[method-name]_data.pkl`, it seems there is no folder named `../log/run/latest`, the correct path for me is `../log/run/DijkstraxDWA/16pillar/37/[method-name]_data.pkl`.

One more issue is that when I run `python3 eval.py`, there is an error of
```
Traceback (most recent call last):
  File "eval.py", line 20, in <module>
    from map_creator import generate_random_maps
ModuleNotFoundError: No module named 'map_creator'
```
I tried to download and put `map_creator.py` under `when2replan/scripts` using this file: https://github.com/ignc-research/arena-rosnav/blob/local_planner_subgoalmode/simulator_setup/maps/map_creator.py
But got error of
```
from map_creator import generate_random_maps
ImportError: cannot import name 'generate_random_maps' from 'map_creator'

```

**Comment by kohonda** [comment]
@robot-Yang 
Hi Yang. Thank you for your valuable feedback. I have updated the README and fixed the errors in the eval (and train) scripts. Thanks again.

**Comment by robot-Yang** [comment]
@kohonda 
Thank you for your effort, I appreciate it.
